name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to AWS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          export PATH="/home/ubuntu/.nvm/versions/node/v22.18.0/bin:$PATH"
          
          cd /var/www/marketing
          git pull origin main
          
          cd server && npm ci --production
          cd ../client && npm ci && npm run build
          cd .. && pm2 restart marketing
          
          sudo systemctl reload nginx