name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: |
          client/package-lock.json
          server/package-lock.json

    - name: Deploy to AWS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /var/www/marketing
          
          # Pull latest changes
          git pull origin main
          
          # Update server dependencies
          cd server
          npm ci
          
          # Build and update client
          cd ../client
          npm ci
          npm run build
          
          # Restart application
          cd ..
          pm2 restart marketing
          
          # Reload nginx
          sudo nginx -t && sudo systemctl reload nginx